name: 'BlazeRunnerAction'
description: 'Run Blazemeter Test from GitHub Action'
inputs:
  apiKey: 
    description: 'API Key'
    required: true
    default: 'Test'
  apiSecret:
    description: 'API Secret'
    required: true
    default: 'Test'
  testId: 
    description: 'Test Id'
    required: true
    default: '0'
  testName: 
    description: 'Test name for creating new test'
    required: false
    default: '0'
  projectId: 
    description: 'Project Id'
    required: false
    default: '0'
  inputStartFile: 
    description: 'Start file for create test'
    required: false
    default: 'null'
  createTest: 
    description: 'Create test flag'
    required: false
    default: 'false'
  totalUsers:
    description: 'total users'
    required: false
    default: '20'
  duration:
    description: 'duration'
    required: false
    default: '20'
  rampUp:
    description: 'rampup'
    required: false
    default: '1'
  uploadFileCheck:
    description: 'upload file'
    required: false
    default: 'false'
  continuePipeline:
    description: 'Continue Pipeline'
    required: false
    default: 'true'
  multiTests:
    description: 'multitests'
    required: false
    default: 'false'
  functionalTest:
    description: 'functionaltest'
    required: false
    default: 'false'
  modelData: 
    description: 'Data to be updated in JSON String format'
    required: false
    default: '{}'
  envVariable:
    description: 'env_variable'
    required: false
    default: '{}'
  showTailLog:
    description: 'showtaillog'
    required: false
    default: 'true'
  jmeterProperties:
    description: 'jmeterproperties'
    required: false
    default: 'null'
  reportName:
    description: 'report name'
    required: false
    default: 'null'
  notes:
    description: 'notes'
    required: false
    default: 'null'
  iterationsConfig:
    description: 'iterations_config'
    required: false
    default: 'false'
  iterations:
    description: 'iterations'
    required: false
    default: '1'
  inputAllFiles:
    description: 'upload dependency file'
    required: false
    default: 'null'
  testRunByTestName:
    description: 'test Run By Test Name'
    required: false
    default: 'false'
  ignoreSLA:
    description: 'job always success'
    required: false
    default: 'false'
  webhookURL:
    description: 'azure team web hook url'
    required: false
    default: 'null'
  enablePublicReportURL:
    description: 'azure team web hook url'
    required: false
    default: 'false'
  
runs:
  using: 'docker'
  image: 'Dockerfile'
  
